/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface BuildExecutionOptions {
  /** Base fee to execute transaction in microcredits */
  baseFee: bigint
  endpoint: string
  functionName: string
  inputs: Array<string>
  /** Priority fee to execute transaction in microcredits */
  priorityFee: bigint
  privateKey: string
  programId: string
  enableLog?: boolean
}
export interface ExecutionResult {
  executionTime: string
  id: string
  /** Execution transaction payload to broadcast */
  transaction: string
}
export declare function buildExecutionTransaction(opts: BuildExecutionOptions): Promise<ExecutionResult>
export declare function loadProgramKeys(): Promise<void>
